version: '3'

services:
  # Nuevo servicio llamado pokedexapp 
  pokedexapp:
    # El servicio depende de la db si la db no se levanta la app tampoco
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: pokedex-docker
    container_name: pokedexapp
    restart: always # Reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"
    # working_dir: /var/www/pokedex
    environment:
      MONGODB: ${MONGODB}
      PORT: ${PORT}
      DEFAULT_LIMIT: ${DEFAULT_LIMIT}
    # volumes:
    #   - ./:/var/www/pokedex
  
  # Imagen de la base de datos de mongo:5
  db:
    image: mongo:5
    container_name: mongo-poke
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-pokemon
    
    # Mantener volumen de la base de datos, que no se nos pierda la data 
    volumes:
      - ./mongo:/data/db